"""initial schema

Revision ID: 56659bf1e07a
Revises: 
Create Date: 2026-09-04 19:39:55.161967+00:00
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = '56659bf1e07a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_providers',
    sa.Column('kind', sa.Enum('LLM', 'IMAGE', 'VIDEO', 'TTS', 'STT', 'STOCK', name='provider_kind', native_enum=False, length=16), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_configured', sa.Boolean(), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('default_model', sa.String(length=120), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('total_requests', sa.Integer(), nullable=False),
    sa.Column('total_failures', sa.Integer(), nullable=False),
    sa.Column('avg_latency_ms', sa.Float(), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_failure_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_providers')),
    sa.UniqueConstraint('kind', 'name', name='uq_ai_providers_kind_name')
    )
    op.create_index('ix_ai_providers_kind_enabled', 'ai_providers', ['kind', 'is_enabled'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('avatar_url', sa.String(length=1024), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('credits_balance', sa.Integer(), nullable=False),
    sa.Column('storage_bytes_used', sa.BigInteger(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('worker_heartbeats',
    sa.Column('worker_id', sa.String(length=120), nullable=False),
    sa.Column('hostname', sa.String(length=200), nullable=False),
    sa.Column('queues', sa.JSON(), nullable=False),
    sa.Column('concurrency', sa.Integer(), nullable=False),
    sa.Column('active_tasks', sa.Integer(), nullable=False),
    sa.Column('processed_total', sa.Integer(), nullable=False),
    sa.Column('failed_total', sa.Integer(), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_worker_heartbeats')),
    sa.UniqueConstraint('worker_id', name=op.f('uq_worker_heartbeats_worker_id'))
    )
    op.create_table('api_keys',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('key_prefix', sa.String(length=20), nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_api_keys_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_keys')),
    sa.UniqueConstraint('key_hash', name=op.f('uq_api_keys_key_hash'))
    )
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('credit_transactions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('GRANT', 'PURCHASE', 'SUBSCRIPTION_RENEWAL', 'CONSUMPTION', 'REFUND', 'ADJUSTMENT', name='credit_tx_kind', native_enum=False, length=32), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_credit_transactions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credit_transactions'))
    )
    op.create_index(op.f('ix_credit_transactions_reference'), 'credit_transactions', ['reference'], unique=False)
    op.create_index('ix_credit_transactions_user_id_created_at', 'credit_transactions', ['user_id', 'created_at'], unique=False)
    op.create_table('projects',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('niche', sa.String(length=100), nullable=True),
    sa.Column('target_audience', sa.String(length=300), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('tone', sa.String(length=60), nullable=False),
    sa.Column('video_format', sa.String(length=60), nullable=False),
    sa.Column('target_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('aspect_ratio', sa.String(length=10), nullable=False),
    sa.Column('resolution', sa.String(length=10), nullable=False),
    sa.Column('visual_style', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'RESEARCHING', 'SCRIPTING', 'STORYBOARDING', 'GENERATING', 'EDITING', 'RENDERING', 'COMPLETED', 'FAILED', 'ARCHIVED', name='project_status', native_enum=False, length=32), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('thumbnail_asset_id', sa.UUID(), nullable=True),
    sa.Column('final_video_asset_id', sa.UUID(), nullable=True),
    sa.Column('estimated_duration_seconds', sa.Float(), nullable=True),
    sa.Column('last_opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_projects_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_index('ix_projects_owner_id_status', 'projects', ['owner_id', 'status'], unique=False)
    op.create_index('ix_projects_owner_id_updated_at', 'projects', ['owner_id', 'updated_at'], unique=False)
    op.create_table('subscriptions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan', sa.Enum('FREE', 'CREATOR', 'PRO', 'STUDIO', name='plan_tier', native_enum=False, length=16), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'TRIALING', 'PAST_DUE', 'CANCELED', 'INCOMPLETE', name='subscription_status', native_enum=False, length=16), nullable=False),
    sa.Column('monthly_credits', sa.Integer(), nullable=False),
    sa.Column('storage_limit_bytes', sa.BigInteger(), nullable=False),
    sa.Column('max_video_minutes', sa.Integer(), nullable=False),
    sa.Column('max_resolution', sa.String(length=10), nullable=False),
    sa.Column('watermark_required', sa.Boolean(), nullable=False),
    sa.Column('concurrent_renders', sa.Integer(), nullable=False),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('payment_provider', sa.String(length=30), nullable=True),
    sa.Column('external_customer_id', sa.String(length=120), nullable=True),
    sa.Column('external_subscription_id', sa.String(length=120), nullable=True),
    sa.Column('external_price_id', sa.String(length=120), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_subscriptions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions')),
    sa.UniqueConstraint('user_id', name=op.f('uq_subscriptions_user_id'))
    )
    op.create_index(op.f('ix_subscriptions_external_customer_id'), 'subscriptions', ['external_customer_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_external_subscription_id'), 'subscriptions', ['external_subscription_id'], unique=False)
    op.create_table('usage_records',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.Enum('LLM_TOKENS', 'RESEARCH', 'SCRIPT', 'TTS_CHARACTERS', 'IMAGE_GENERATION', 'VIDEO_GENERATION', 'STT_SECONDS', 'RENDER_SECONDS', 'STORAGE_BYTES', name='usage_kind', native_enum=False, length=32), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_usage_records_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usage_records'))
    )
    op.create_index('ix_usage_records_project_id', 'usage_records', ['project_id'], unique=False)
    op.create_index('ix_usage_records_user_id_period_kind', 'usage_records', ['user_id', 'period', 'kind'], unique=False)
    op.create_table('user_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=128), nullable=False),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_sessions'))
    )
    op.create_index(op.f('ix_user_sessions_refresh_token_hash'), 'user_sessions', ['refresh_token_hash'], unique=False)
    op.create_index('ix_user_sessions_user_id_expires_at', 'user_sessions', ['user_id', 'expires_at'], unique=False)
    op.create_table('audio_assets',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.Enum('VOICEOVER', 'MUSIC', 'SFX', name='audio_kind', native_enum=False, length=16), nullable=False),
    sa.Column('source', sa.Enum('UPLOAD', 'AI_IMAGE', 'AI_VIDEO', 'STOCK', 'RENDER', 'SYSTEM', name='media_source', native_enum=False, length=16), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('sample_rate', sa.Integer(), nullable=True),
    sa.Column('mood', sa.String(length=60), nullable=True),
    sa.Column('bpm', sa.Integer(), nullable=True),
    sa.Column('license', sa.String(length=120), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_audio_assets_owner_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_audio_assets_project_id_projects'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audio_assets')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_audio_assets_storage_key'))
    )
    op.create_index('ix_audio_assets_owner_id_kind', 'audio_assets', ['owner_id', 'kind'], unique=False)
    op.create_table('captions',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('cues', sa.JSON(), nullable=False),
    sa.Column('style', sa.JSON(), nullable=False),
    sa.Column('srt_storage_key', sa.String(length=1024), nullable=True),
    sa.Column('vtt_storage_key', sa.String(length=1024), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('cue_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_captions_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_captions'))
    )
    op.create_index('ix_captions_project_id_is_current', 'captions', ['project_id', 'is_current'], unique=False)
    op.create_table('generation_jobs',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('job_type', sa.Enum('RESEARCH', 'SCRIPT', 'SCRIPT_SECTION', 'SCENES', 'VOICEOVER', 'VISUALS', 'CAPTIONS', 'FULL_PIPELINE', 'RENDER', 'PREVIEW_RENDER', name='job_type', native_enum=False, length=32), nullable=False),
    sa.Column('parent_job_id', sa.UUID(), nullable=True),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('state', sa.Enum('QUEUED', 'PROCESSING', 'RESEARCHING', 'GENERATING_SCRIPT', 'GENERATING_SCENES', 'GENERATING_AUDIO', 'GENERATING_VISUALS', 'GENERATING_CAPTIONS', 'RENDERING', 'UPLOADING', 'COMPLETED', 'FAILED', 'CANCELLED', name='job_state', native_enum=False, length=32), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=120), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('celery_task_id', sa.String(length=64), nullable=True),
    sa.Column('worker_id', sa.String(length=120), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('error_details', sa.JSON(), nullable=False),
    sa.Column('logs', sa.JSON(), nullable=False),
    sa.Column('eta_seconds', sa.Integer(), nullable=True),
    sa.Column('credits_reserved', sa.Integer(), nullable=False),
    sa.Column('credits_charged', sa.Integer(), nullable=False),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_job_id'], ['generation_jobs.id'], name=op.f('fk_generation_jobs_parent_job_id_generation_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_generation_jobs_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_generation_jobs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_generation_jobs'))
    )
    op.create_index('ix_generation_jobs_project_id_created_at', 'generation_jobs', ['project_id', 'created_at'], unique=False)
    op.create_index('ix_generation_jobs_state_queued_at', 'generation_jobs', ['state', 'queued_at'], unique=False)
    op.create_index('ix_generation_jobs_user_id_state', 'generation_jobs', ['user_id', 'state'], unique=False)
    op.create_index('uq_generation_jobs_idempotency', 'generation_jobs', ['user_id', 'idempotency_key'], unique=True, postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.create_table('media_assets',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('scene_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.Enum('IMAGE', 'VIDEO', 'AUDIO', 'FONT', 'SUBTITLE', 'OTHER', name='media_kind', native_enum=False, length=16), nullable=False),
    sa.Column('source', sa.Enum('UPLOAD', 'AI_IMAGE', 'AI_VIDEO', 'STOCK', 'RENDER', 'SYSTEM', name='media_source', native_enum=False, length=16), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('thumbnail_key', sa.String(length=1024), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=60), nullable=True),
    sa.Column('provider_ref', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('is_reusable', sa.Boolean(), nullable=False),
    sa.Column('is_uploaded', sa.Boolean(), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_media_assets_owner_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_media_assets_project_id_projects'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_assets')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_media_assets_storage_key'))
    )
    op.create_index('ix_media_assets_owner_id_kind', 'media_assets', ['owner_id', 'kind'], unique=False)
    op.create_index('ix_media_assets_project_id_kind', 'media_assets', ['project_id', 'kind'], unique=False)
    op.create_index('ix_media_assets_scene_id', 'media_assets', ['scene_id'], unique=False)
    op.create_table('research',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('sections', sa.JSON(), nullable=False),
    sa.Column('key_facts', sa.JSON(), nullable=False),
    sa.Column('statistics', sa.JSON(), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=False),
    sa.Column('suggested_angles', sa.JSON(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_research_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research')),
    sa.UniqueConstraint('project_id', name=op.f('uq_research_project_id'))
    )
    op.create_table('scripts',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('hook', sa.Text(), nullable=True),
    sa.Column('outline', sa.JSON(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('estimated_duration_seconds', sa.Float(), nullable=False),
    sa.Column('target_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('words_per_minute', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_scripts_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scripts')),
    sa.UniqueConstraint('project_id', 'version', name='uq_scripts_project_version')
    )
    op.create_index('ix_scripts_project_id_is_current', 'scripts', ['project_id', 'is_current'], unique=False)
    op.create_table('timelines',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('fps', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('snapshots', sa.JSON(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_timelines_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_timelines')),
    sa.UniqueConstraint('project_id', name=op.f('uq_timelines_project_id'))
    )
    op.create_table('render_jobs',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('is_preview', sa.Boolean(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('fps', sa.Integer(), nullable=False),
    sa.Column('format', sa.String(length=16), nullable=False),
    sa.Column('burn_captions', sa.Boolean(), nullable=False),
    sa.Column('include_watermark', sa.Boolean(), nullable=False),
    sa.Column('timeline_version', sa.Integer(), nullable=True),
    sa.Column('timeline_snapshot', sa.JSON(), nullable=False),
    sa.Column('output_asset_id', sa.UUID(), nullable=True),
    sa.Column('output_duration_seconds', sa.Float(), nullable=True),
    sa.Column('output_size_bytes', sa.Integer(), nullable=True),
    sa.Column('render_seconds', sa.Float(), nullable=True),
    sa.Column('state', sa.Enum('QUEUED', 'PROCESSING', 'RESEARCHING', 'GENERATING_SCRIPT', 'GENERATING_SCENES', 'GENERATING_AUDIO', 'GENERATING_VISUALS', 'GENERATING_CAPTIONS', 'RENDERING', 'UPLOADING', 'COMPLETED', 'FAILED', 'CANCELLED', name='job_state', native_enum=False, length=32), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=120), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('celery_task_id', sa.String(length=64), nullable=True),
    sa.Column('worker_id', sa.String(length=120), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('error_details', sa.JSON(), nullable=False),
    sa.Column('logs', sa.JSON(), nullable=False),
    sa.Column('eta_seconds', sa.Integer(), nullable=True),
    sa.Column('credits_reserved', sa.Integer(), nullable=False),
    sa.Column('credits_charged', sa.Integer(), nullable=False),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['output_asset_id'], ['media_assets.id'], name=op.f('fk_render_jobs_output_asset_id_media_assets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_render_jobs_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_render_jobs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_render_jobs'))
    )
    op.create_index('ix_render_jobs_project_id_created_at', 'render_jobs', ['project_id', 'created_at'], unique=False)
    op.create_index('ix_render_jobs_user_id_state', 'render_jobs', ['user_id', 'state'], unique=False)
    op.create_index('uq_render_jobs_idempotency', 'render_jobs', ['user_id', 'idempotency_key'], unique=True, postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.create_table('script_sections',
    sa.Column('script_id', sa.UUID(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('HOOK', 'INTRO', 'BODY', 'TRANSITION', 'STORY', 'CONCLUSION', 'CTA', name='section_kind', native_enum=False, length=32), nullable=False),
    sa.Column('heading', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('talking_points', sa.JSON(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('estimated_duration_seconds', sa.Float(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('regeneration_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], name=op.f('fk_script_sections_script_id_scripts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_script_sections'))
    )
    op.create_index('ix_script_sections_script_id_order', 'script_sections', ['script_id', 'order_index'], unique=False)
    op.create_table('scenes',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('narration', sa.Text(), nullable=False),
    sa.Column('visual_description', sa.Text(), nullable=True),
    sa.Column('suggested_footage', sa.Text(), nullable=True),
    sa.Column('image_prompt', sa.Text(), nullable=True),
    sa.Column('video_prompt', sa.Text(), nullable=True),
    sa.Column('negative_prompt', sa.Text(), nullable=True),
    sa.Column('on_screen_text', sa.String(length=300), nullable=True),
    sa.Column('visual_type', sa.Enum('AI_IMAGE', 'AI_VIDEO', 'STOCK_VIDEO', 'STOCK_IMAGE', 'UPLOAD', 'TEXT_CARD', name='visual_type', native_enum=False, length=32), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('transition', sa.String(length=40), nullable=False),
    sa.Column('transition_duration', sa.Float(), nullable=False),
    sa.Column('motion_effect', sa.String(length=40), nullable=False),
    sa.Column('music_suggestion', sa.String(length=200), nullable=True),
    sa.Column('music_mood', sa.String(length=60), nullable=True),
    sa.Column('sound_effects', sa.JSON(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('visual_asset_id', sa.UUID(), nullable=True),
    sa.Column('voiceover_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_scenes_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['script_sections.id'], name=op.f('fk_scenes_section_id_script_sections'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['visual_asset_id'], ['media_assets.id'], name=op.f('fk_scenes_visual_asset_id_media_assets'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenes'))
    )
    op.create_index('ix_scenes_project_id_order', 'scenes', ['project_id', 'order_index'], unique=False)
    op.create_table('voiceovers',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('scene_id', sa.UUID(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('text_hash', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('voice_id', sa.String(length=120), nullable=False),
    sa.Column('voice_name', sa.String(length=120), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('style', sa.String(length=60), nullable=True),
    sa.Column('speed', sa.Float(), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=True),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('word_timings', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_voiceovers_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], name=op.f('fk_voiceovers_scene_id_scenes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_voiceovers'))
    )
    op.create_index('ix_voiceovers_project_id_scene_id', 'voiceovers', ['project_id', 'scene_id'], unique=False)
    op.create_index('ix_voiceovers_text_hash_voice', 'voiceovers', ['text_hash', 'voice_id', 'provider'], unique=False)
    # scenes <-> voiceovers is circular; add the second FK once both tables exist.
    op.create_foreign_key(op.f('fk_scenes_voiceover_id_voiceovers'), 'scenes', 'voiceovers', ['voiceover_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_scenes_voiceover_id_voiceovers'), 'scenes', type_='foreignkey')
    op.drop_index('ix_voiceovers_text_hash_voice', table_name='voiceovers')
    op.drop_index('ix_voiceovers_project_id_scene_id', table_name='voiceovers')
    op.drop_table('voiceovers')
    op.drop_index('ix_scenes_project_id_order', table_name='scenes')
    op.drop_table('scenes')
    op.drop_index('ix_script_sections_script_id_order', table_name='script_sections')
    op.drop_table('script_sections')
    op.drop_index('uq_render_jobs_idempotency', table_name='render_jobs', postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.drop_index('ix_render_jobs_user_id_state', table_name='render_jobs')
    op.drop_index('ix_render_jobs_project_id_created_at', table_name='render_jobs')
    op.drop_table('render_jobs')
    op.drop_table('timelines')
    op.drop_index('ix_scripts_project_id_is_current', table_name='scripts')
    op.drop_table('scripts')
    op.drop_table('research')
    op.drop_index('ix_media_assets_scene_id', table_name='media_assets')
    op.drop_index('ix_media_assets_project_id_kind', table_name='media_assets')
    op.drop_index('ix_media_assets_owner_id_kind', table_name='media_assets')
    op.drop_table('media_assets')
    op.drop_index('uq_generation_jobs_idempotency', table_name='generation_jobs', postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.drop_index('ix_generation_jobs_user_id_state', table_name='generation_jobs')
    op.drop_index('ix_generation_jobs_state_queued_at', table_name='generation_jobs')
    op.drop_index('ix_generation_jobs_project_id_created_at', table_name='generation_jobs')
    op.drop_table('generation_jobs')
    op.drop_index('ix_captions_project_id_is_current', table_name='captions')
    op.drop_table('captions')
    op.drop_index('ix_audio_assets_owner_id_kind', table_name='audio_assets')
    op.drop_table('audio_assets')
    op.drop_index('ix_user_sessions_user_id_expires_at', table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_refresh_token_hash'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index('ix_usage_records_user_id_period_kind', table_name='usage_records')
    op.drop_index('ix_usage_records_project_id', table_name='usage_records')
    op.drop_table('usage_records')
    op.drop_index(op.f('ix_subscriptions_external_subscription_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_external_customer_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index('ix_projects_owner_id_updated_at', table_name='projects')
    op.drop_index('ix_projects_owner_id_status', table_name='projects')
    op.drop_table('projects')
    op.drop_index('ix_credit_transactions_user_id_created_at', table_name='credit_transactions')
    op.drop_index(op.f('ix_credit_transactions_reference'), table_name='credit_transactions')
    op.drop_table('credit_transactions')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_table('worker_heartbeats')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_ai_providers_kind_enabled', table_name='ai_providers')
    op.drop_table('ai_providers')
    # ### end Alembic commands ###
