import Link from "next/link";
import { ArrowRight, Sparkles, Mic2, Image as ImageIcon, Captions, Film, Layers, ShieldCheck, Workflow, Clapperboard } from "lucide-react";

const steps = [
  { icon: Sparkles, title: "Research", text: "Facts, statistics, sources and narrative angles, organised into sections you can edit before a single line is written." },
  { icon: Layers, title: "Script", text: "Hook, intro, chapters, transitions, conclusion and CTA — 5 to 60+ minutes, regenerate any section, live word count and runtime." },
  { icon: Clapperboard, title: "Storyboard", text: "Scenes with narration, visual direction, AI image/video prompts, on-screen text, transitions and music cues." },
  { icon: Mic2, title: "Voiceover", text: "Natural TTS in dozens of voices, languages and styles. Per-scene narration with word-level timings." },
  { icon: ImageIcon, title: "Visuals", text: "AI images, AI video clips, stock footage or your uploads — swap or regenerate any single shot." },
  { icon: Captions, title: "Captions", text: "SRT/VTT generated from the narration, styled and burned in with animation and precise timing." },
  { icon: Film, title: "Render", text: "FFmpeg pipeline: Ken Burns motion, transitions, ducked music, overlays, intro/outro and 4K MP4 export." },
];

export default function Landing() {
  return (
    <main className="min-h-screen">
      <header className="sticky top-0 z-30 border-b border-line/60 bg-bg/80 backdrop-blur">
        <div className="mx-auto flex max-w-6xl items-center justify-between px-6 py-4">
          <Link href="/" className="flex items-center gap-2 font-semibold">
            <span className="grid h-7 w-7 place-items-center rounded-lg bg-brand-500 text-white shadow-glow"><Film className="h-4 w-4" /></span>
            LongForm AI
          </Link>
          <nav className="flex items-center gap-2 text-sm">
            <a href="/api/v1/docs" className="btn-ghost hidden sm:inline-flex" target="_blank" rel="noreferrer">API docs</a>
            <Link href="/login" className="btn-ghost">Log in</Link>
            <Link href="/signup" className="btn-primary">Start free <ArrowRight className="h-4 w-4" /></Link>
          </nav>
        </div>
      </header>

      <section className="relative overflow-hidden">
        <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(ellipse_at_top,rgba(58,95,255,0.25),transparent_60%)]" />
        <div className="mx-auto max-w-6xl px-6 pb-20 pt-24 text-center">
          <span className="badge mx-auto border-brand-500/40 bg-brand-500/10 text-brand-200">AI video production pipeline · not just an editor</span>
          <h1 className="mx-auto mt-6 max-w-3xl text-balance text-4xl font-semibold tracking-tight sm:text-6xl">
            From a topic to a finished <span className="bg-gradient-to-r from-brand-300 to-accent bg-clip-text text-transparent">long-form video</span>
          </h1>
          <p className="mx-auto mt-6 max-w-2xl text-balance text-lg text-muted">
            Research, script, storyboard, voiceover, visuals, captions and a rendered 1080p/4K MP4 — generated by background workers, reviewed and refined by you in a real multi-track editor.
          </p>
          <div className="mt-8 flex items-center justify-center gap-3">
            <Link href="/signup" className="btn-primary px-6 py-3 text-base">Create your first video</Link>
            <Link href="/login" className="btn-secondary px-6 py-3 text-base">Open studio</Link>
          </div>
          <p className="mt-4 text-xs text-muted">500 free credits · no card required · bring your own AI provider keys or use the built-in dev providers</p>
        </div>
      </section>

      <section className="mx-auto max-w-6xl px-6 pb-24">
        <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
          {steps.map((s, i) => (
            <div key={s.title} className="card p-5">
              <div className="flex items-center justify-between">
                <span className="rounded-lg bg-brand-500/10 p-2 text-brand-300"><s.icon className="h-5 w-5" /></span>
                <span className="font-mono text-xs text-muted">0{i + 1}</span>
              </div>
              <h3 className="mt-4 font-semibold">{s.title}</h3>
              <p className="mt-1 text-sm text-muted">{s.text}</p>
            </div>
          ))}
          <div className="card flex flex-col justify-between bg-gradient-to-br from-brand-600/30 to-panel p-5">
            <div>
              <span className="rounded-lg bg-white/10 p-2 text-white"><Workflow className="h-5 w-5 inline" /></span>
              <h3 className="mt-4 font-semibold">Built to scale</h3>
              <p className="mt-1 text-sm text-muted">Celery workers, Redis queues, Postgres job tracking, S3 storage with signed URLs, SSE progress, retries, idempotency and cancellation.</p>
            </div>
            <div className="mt-4 flex items-center gap-2 text-xs text-muted"><ShieldCheck className="h-4 w-4" /> Keys stay on the server — never in the browser.</div>
          </div>
        </div>
      </section>

      <footer className="border-t border-line/60 py-8 text-center text-xs text-muted">© {new Date().getFullYear()} LongForm AI · FastAPI · Next.js · FFmpeg</footer>
    </main>
  );
}
